services:
  mysql:
    image: mysql:8.4
    container_name: sd_mysql
    environment:
      MYSQL_DATABASE: security_depot_fsm
      MYSQL_USER: sd_user
      MYSQL_PASSWORD: sd_password
      MYSQL_ROOT_PASSWORD: sd_root_password
    ports:
      - "3307:3306"
    volumes:
      - sd_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-usd_user", "-psd_password"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  sd_mysql_data:
